version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: comparatron-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: comparatron
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - comparatron-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/comparatron --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express - Web-based MongoDB admin interface (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: comparatron-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - comparatron-network

  # Next.js application (optional - can also run locally)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comparatron-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/comparatron?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-this-in-production}
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NODE_ENV: development
    volumes:
      # Mount source code for hot reload in development
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - comparatron-network
    command: npm run dev

networks:
  comparatron-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
